### ISSUE TITLE
Update to 1.19.3 Please

### ISSUE THREAD

**Issue by sternschnaube** [Splzh/ClearHitboxes#2]
**Hello, this is the crash log, it comes after I pressed F3+B:**
java.lang.NoSuchMethodError: 'net.minecraft.class_1159 net.minecraft.class_4587$class_4665.method_23761()'
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at splash.utils.BoxUtils.drawBoxThin(BoxUtils.java:19)
	at splash.utils.Render.drawBox(Render.java:23)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.handler$cpj000$renderHitbox(EntityRenderDispatcher:1035)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.renderHitbox(EntityRenderDispatcher)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:158)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1569)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1316)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1085)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:864)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1193)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:781)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**While I have Anaglyph Fabric installed, the crash log looks like this:**
java.lang.NoSuchMethodError: 'net.minecraft.class_1159 net.minecraft.class_4587$class_4665.method_23761()'
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at splash.utils.BoxUtils.drawBoxThin(BoxUtils.java:19)
	at splash.utils.Render.drawBox(Render.java:23)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.handler$cpm000$renderHitbox(EntityRenderDispatcher:1035)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.renderHitbox(EntityRenderDispatcher)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:158)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1569)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1316)
	at net.minecraft.client.render.GameRenderer.md10bbb5$lambda$renderWorldTwice$0$1(GameRenderer:2578)
	at vlad2305m.anaglyphfabric.client.Util.renderTwice(Util.java:45)
	at net.minecraft.client.render.GameRenderer.redirect$zzk000$renderWorldTwice(GameRenderer:2577)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1085)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:864)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1193)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:781)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

But I think this is not connected - the mod: https://github.com/vlad2305m/Anaglyph-fabric

**Comment by ghost** [comment]
yo i made a fork for 1.19.3

**Comment by Longie520** [comment]
> yo i made a fork for 1.19.3

hi can you please make a fork for 1.19.4 too?? thank you!

**Comment by ghost** [comment]
Probably will do shortly

**Comment by sternschnaube** [comment]
Thanks.
https://legacy.curseforge.com/minecraft/mc-mods/clear-hitboxes/files/4523687
